/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativewrapper_NativeWrapper */

#ifndef _Included_nativewrapper_NativeWrapper
#define _Included_nativewrapper_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativewrapper_NativeWrapper
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativewrapper_NativeWrapper_printHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
